### ISSUE TITLE
Tool flexibility for a given processing task

### ISSUE THREAD

**Issue by vreuter** [epigen/pypiper#44]
Since processing tasks that are common to a variety of pipelines often are implemented as different tools, and since some use cases or environments may not have the full array of tools for a given task installed or otherwise available, or a pipeline may wish to use a particular tool for the given task, it'd be a nice feature (maybe in `NGSTK`) to provide this sort of tool substitution flexibility. For instance, `filterReads` could use `samtools` or `sambamba`. While individual pipelines could independently implement this sort of logic, it could substantially reduce code duplication and simplify the process of pipeline authorship to roll this sort of tool parameterization into `NGSTK` itself. This could be done in a number of ways, from independent functions, to a function like `filterReads` accepting one or more other functions as arguments, to something like a `ReadFilter` class in which the tool of choice and filtration parameters could be supplied at construction time or at call time.

**Comment by nsheff** [comment]
this is exactly what is implemented in the `ngstk.ziptool` attribute. since `pigz` is a drop-in parallel replacement for `gzip`, `ngstk` can simply check if `pigz` is installed, and if so, use that, and the user benefits from parallel processing all compression/uncompression used anywhere in the pipeline. if not, it drops back to `gzip`, no harm done.

there's no reason we couldn't do exactly the same thing for `samtools` and `sambamba`.

It's quite simple, see: 

https://github.com/epigen/pypiper/blob/494d1ff2d45a08095d28dbc687afe1acbb7823fe/pypiper/ngstk.py#L61-L65

The pipeline author just has to use `ngstk.ziptool` instead of `gzip` or `pigz` to use this functionality.
It only works if they really are drop-in replacements, though.

**Comment by nsheff** [comment]
one thing I like about this is that it's 4 lines of code. easy to maintain, easy to understand. I'd prefer this over layers of functions, personally, because of reduced overhead. but there are probably other ways to accomplish the same thing.

**Comment by vreuter** [comment]
Hm yeah I think there are good aspects to each. In general, I think a significantly more flexible framework that may entail a bit more complexity would be something to probe for, but I haven't looked around much for the extent of common processing functions to which this may apply.

For the read filtration in particular, though, I think that an analog to the `ziptool` strategy would work well, assuming (sort of like with a default arg, I guess), that `samtools` plays the role of `pigz` and should be favored in a sufficiently significant preponderance of use cases. Or vice-versa, I guess, with `sambamba` as the default. Is that the case, that you think it's appropriate to favor one over the other? I don't know about their usage frequency, but from discussion yesterday it sounds like `samtools` is the more frequent/preferred one?

**Comment by nsheff** [comment]
well... To me samtools is the default.

personally, I wouldn't even bother investing any effort in samtools vs sambamba. just use `samtools` and call it done. I have seen very little use of `sambamba` and it was years ago. just my 2 cents.

**Comment by vreuter** [comment]
I understand what this means, but this delves into the realm of what constitutes a _default_ versus a _fallback_. I would call the role sambamba plays here "default" and samtools the "fallback."

**Comment by nsheff** [comment]
semantics.
